import { randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import path from "node:path";
import {
    BASELINE_DEPENDENCIES,
    BASELINE_BEBE_DEPENDENCIES,
    BASELINE_DEV_DEPENDENCIES,
    BASELINE_TYPESCRIPT_DEPENDENCIES,
    BLR_CONFIG_FILE,
    BLR_CONFIG_SCHEMA_PATH,
    CURRENT_PROJECT_VERSION,
    DEFAULT_BDS_WORLD_NAME,
    DEFAULT_MINECRAFT_TARGET_VERSION,
    DEFAULT_MIN_ENGINE_VERSION,
    DEFAULT_PACK_VERSION,
    PACKAGE_MANAGER_VERSION_HINTS,
} from "../constants.js";
import {
    ensureDirectory,
    exists,
    isDirectoryEmpty,
    removeDirectory,
    writeJson,
    writeText,
} from "../fs.js";
import { syncManagedProjectInstructions } from "../project-instructions.js";
import {
    MANAGED_PACKAGE_SCRIPTS,
    reconcileManagedGitIgnore,
} from "../managed-project.js";
import { runPrompt } from "../prompt.js";
import type {
    BlurConfigFile,
    Language,
    PackageManager,
    VersionTuple,
} from "../types.js";
import {
    assertValidNamespace,
    getCliPackageVersion,
    normalizeNamespace,
    parseLanguage,
    parsePackageManager,
    resolvePmExecutable,
    toPackageName,
    toPackName,
} from "../utils.js";

type CreateCommandOptions = {
    namespace?: string;
    packageManager?: string;
    behaviorPack?: boolean;
    resourcePack?: boolean;
    language?: string;
    scripts?: boolean;
    bebe?: boolean;
    yes?: boolean;
    force?: boolean;
    install?: boolean;
};

type CreateResolvedOptions = {
    projectDirectory: string;
    projectName: string;
    namespace: string;
    packageManager: PackageManager;
    behaviorPack: boolean;
    resourcePack: boolean;
    scripts: boolean;
    bebe: boolean;
    language: Language;
    force: boolean;
    install: boolean;
};

type PackageJsonShape = {
    name: string;
    version: string;
    description: string;
    private: boolean;
    type: "module";
    packageManager?: string;
    scripts: Record<string, string>;
    dependencies: Record<string, string>;
    devDependencies: Record<string, string>;
    engines: {
        node: string;
    };
};

function stripVersionRange(version: string): string {
    return version.replace(/^[~^]/, "");
}

const DEFAULT_CREATE_BEBE_ENABLED = false;

function renderMainFile(bebe: boolean): string {
    if (!bebe) {
        return ["export {};", ""].join("\n");
    }

    return [
        'import { Context } from "@blurengine/bebe";',
        "",
        "const ctx = new Context();",
        "ctx.onDispose(() => {});",
        "",
        "export { ctx };",
        "",
    ].join("\n");
}

function renderTsConfig(): string {
    return `${JSON.stringify(
        {
            compilerOptions: {
                target: "ES2022",
                module: "NodeNext",
                moduleResolution: "NodeNext",
                strict: true,
                noEmit: true,
                skipLibCheck: true,
                resolveJsonModule: true,
            },
            include: ["src/**/*.ts"],
        },
        null,
        2,
    )}\n`;
}

function renderPackageManagerRunCommand(
    packageManager: PackageManager,
    scriptName: string,
    trailingArgs = "",
): string {
    const suffix = trailingArgs.length > 0 ? ` ${trailingArgs}` : "";
    return `${packageManager} run ${scriptName}${suffix}`;
}

function renderReadme(
    projectName: string,
    packName: string,
    packageManager: PackageManager,
    features: {
        behaviorPack: boolean;
        resourcePack: boolean;
        scripts: boolean;
        bebe: boolean;
    },
): string {
    const structureLines = [
        ...(features.behaviorPack
            ? [
                  `- \`behavior_packs/${packName}/\` -> authored behavior-pack content`,
              ]
            : []),
        ...(features.resourcePack
            ? [
                  `- \`resource_packs/${packName}/\` -> authored resource-pack content`,
              ]
            : []),
        ...(features.scripts
            ? [
                  "- `src/` -> authored Bedrock runtime source that bundles into the behavior pack",
              ]
            : []),
        `- \`worlds/${DEFAULT_BDS_WORLD_NAME}/\` -> optional raw project world source when you choose to keep one locally`,
        "- `server/` -> optional retained server state such as allowlist and permissions",
        "- `dist/` -> generated staged build output and packaged artifacts",
        "- `.blr/` -> local CLI runtime workspace, cache, and dev state",
    ];

    return [
        `# ${projectName}`,
        "",
        "BlurEngine project generated by `@blurengine/cli`.",
        "",
        "## Structure",
        "",
        ...structureLines,
        "",
        "## Commands",
        "",
        `- \`${renderPackageManagerRunCommand(packageManager, "dev")}\` -> interactive local development workflow`,
        `- \`${renderPackageManagerRunCommand(packageManager, "build")}\` -> stage canonical build output into \`dist/stage\``,
        `- \`${renderPackageManagerRunCommand(packageManager, "package")}\` -> produce the default package artifact in \`dist/packages\``,
        `- \`${renderPackageManagerRunCommand(packageManager, "minecraft", "-- <subcommand>")}\` -> check or update the configured Minecraft target version`,
        `- \`${renderPackageManagerRunCommand(packageManager, "system", "-- <subcommand>")}\` -> print support diagnostics about the current environment and project`,
        `- \`${renderPackageManagerRunCommand(packageManager, "world", "-- <subcommand>")}\` -> manage project world sources and remote world storage`,
        `- \`${renderPackageManagerRunCommand(packageManager, "clean")}\` -> remove \`dist/\``,
        `- \`${renderPackageManagerRunCommand(packageManager, "upgrade")}\` -> align managed scaffold files and dependency baseline`,
        "",
        "## Notes",
        "",
        "- keep shared project settings in `blr.config.json`",
        "- keep secrets and machine-local overrides in `.env.local`",
        "- world-aware flows require that folder to contain a real Bedrock world with a `db/` directory.",
        "- `server/allowlist.json` and `server/permissions.json` are optional project state files that `blr` applies to BDS when present.",
        ...(features.scripts && !features.bebe
            ? [
                  "- scripting is enabled without `@blurengine/bebe`; add it later if you want the BlurEngine runtime helpers.",
              ]
            : []),
        ...(features.scripts
            ? []
            : [
                  "",
                  "- This project was generated without scripting enabled.",
                  "- Add `src/main.ts` or `src/main.js` later when you want Bedrock script runtime behavior. `blr` will detect it automatically.",
              ]),
        "",
    ].join("\n");
}

function createPackageJson(
    projectName: string,
    packageName: string,
    packageManager: PackageManager,
    scripts: boolean,
    bebe: boolean,
    language: Language,
    cliVersion: string,
): PackageJsonShape {
    const dependencies = scripts
        ? Object.fromEntries(
              Object.entries(BASELINE_DEPENDENCIES).map(([name, version]) => [
                  name,
                  version,
              ]),
          )
        : {};
    if (scripts && bebe) {
        Object.assign(dependencies, BASELINE_BEBE_DEPENDENCIES);
    }
    const devDependencies: Record<string, string> = {
        ...BASELINE_DEV_DEPENDENCIES,
        "@blurengine/cli": `^${cliVersion}`,
    };

    if (scripts && language === "ts") {
        Object.assign(devDependencies, BASELINE_TYPESCRIPT_DEPENDENCIES);
    }

    return {
        name: packageName,
        version: "0.1.0",
        description: `${projectName} BlurEngine project`,
        private: true,
        type: "module",
        packageManager: PACKAGE_MANAGER_VERSION_HINTS[packageManager],
        scripts: { ...MANAGED_PACKAGE_SCRIPTS },
        dependencies,
        devDependencies,
        engines: {
            node: ">=20.0.0",
        },
    };
}

type LocalDependencyOverrides = {
    dependencies: Record<string, string>;
    devDependencies: Record<string, string>;
};

function asPortableRelativeFileSpec(fromPath: string, toPath: string): string {
    const raw = path.relative(fromPath, toPath);
    const normalized = raw.split(path.sep).join("/");
    return `file:${normalized.startsWith(".") ? normalized : `./${normalized}`}`;
}

async function resolveLocalDependencyOverrides(
    projectRoot: string,
): Promise<LocalDependencyOverrides> {
    let scanRoot = projectRoot;
    let workspaceRoot: string | undefined;
    while (true) {
        const bebeCandidate = path.join(scanRoot, "bebe");
        const cliCandidate = path.join(scanRoot, "cli", "packages", "blr");
        if ((await exists(bebeCandidate)) && (await exists(cliCandidate))) {
            workspaceRoot = scanRoot;
            break;
        }
        const parent = path.dirname(scanRoot);
        if (parent === scanRoot) break;
        scanRoot = parent;
    }

    if (!workspaceRoot) {
        return { dependencies: {}, devDependencies: {} };
    }

    return {
        dependencies: {
            "@blurengine/bebe": asPortableRelativeFileSpec(
                projectRoot,
                path.join(workspaceRoot, "bebe"),
            ),
        },
        devDependencies: {
            "@blurengine/cli": asPortableRelativeFileSpec(
                projectRoot,
                path.join(workspaceRoot, "cli", "packages", "blr"),
            ),
        },
    };
}

function createBehaviorManifest(
    projectName: string,
    version: VersionTuple,
    scripts: boolean,
): Record<string, unknown> {
    return {
        format_version: 2,
        header: {
            name: `${projectName} Behavior Pack`,
            description: `${projectName} behavior pack`,
            uuid: randomUUID(),
            version,
            min_engine_version: DEFAULT_MIN_ENGINE_VERSION,
        },
        modules: [
            {
                description: "Behavior resources",
                type: "data",
                uuid: randomUUID(),
                version,
            },
            ...(scripts
                ? [
                      {
                          description: "Script resources",
                          language: "javascript",
                          type: "script",
                          uuid: randomUUID(),
                          version,
                          entry: "scripts/main.js",
                      },
                  ]
                : []),
        ],
        ...(scripts
            ? {
                  dependencies: [
                      {
                          module_name: "@minecraft/server",
                          version: stripVersionRange(
                              BASELINE_DEPENDENCIES["@minecraft/server"],
                          ),
                      },
                      {
                          module_name: "@minecraft/server-ui",
                          version: stripVersionRange(
                              BASELINE_DEPENDENCIES["@minecraft/server-ui"],
                          ),
                      },
                      {
                          module_name: "@minecraft/server-admin",
                          version: stripVersionRange(
                              BASELINE_DEPENDENCIES["@minecraft/server-admin"],
                          ),
                      },
                      {
                          module_name: "@minecraft/server-net",
                          version: stripVersionRange(
                              BASELINE_DEPENDENCIES["@minecraft/server-net"],
                          ),
                      },
                  ],
              }
            : {}),
    };
}

function createResourceManifest(
    projectName: string,
    version: VersionTuple,
): Record<string, unknown> {
    return {
        format_version: 2,
        header: {
            name: `${projectName} Resource Pack`,
            description: `${projectName} resource pack`,
            uuid: randomUUID(),
            version,
            min_engine_version: DEFAULT_MIN_ENGINE_VERSION,
        },
        modules: [
            {
                type: "resources",
                uuid: randomUUID(),
                version,
            },
        ],
    };
}

async function resolveCreateOptions(
    projectArg: string | undefined,
    options: CreateCommandOptions,
): Promise<CreateResolvedOptions> {
    const skipPrompts = Boolean(options.yes);

    let projectDirectory = String(projectArg ?? "").trim();
    if (!projectDirectory && !skipPrompts) {
        const answers = await runPrompt({
            type: "text",
            name: "projectName",
            message: "Project name",
            validate: (value: string) =>
                value.trim().length > 0 ? true : "Project name is required.",
        });
        projectDirectory = String(answers.projectName ?? "").trim();
    }

    let namespaceInput = String(options.namespace ?? "").trim();
    if (!namespaceInput && !skipPrompts) {
        const answers = await runPrompt({
            type: "text",
            name: "namespace",
            message: "Namespace",
            validate: (value: string) =>
                value.trim().length > 0 ? true : "Namespace is required.",
        });
        namespaceInput = String(answers.namespace ?? "").trim();
    }

    let behaviorPack =
        typeof options.behaviorPack === "boolean" ? options.behaviorPack : true;
    let resourcePack =
        typeof options.resourcePack === "boolean" ? options.resourcePack : true;
    let scripts = typeof options.scripts === "boolean" ? options.scripts : true;
    let bebe =
        typeof options.bebe === "boolean"
            ? options.bebe
            : DEFAULT_CREATE_BEBE_ENABLED;
    let advanced = false;
    const shouldPromptProjectFeatures =
        !skipPrompts &&
        typeof options.behaviorPack !== "boolean" &&
        typeof options.resourcePack !== "boolean";
    if (shouldPromptProjectFeatures) {
        while (true) {
            const answers = await runPrompt({
                type: "multiselect",
                name: "features",
                message: "Enable project features",
                choices: [
                    {
                        title: "Behavior pack",
                        value: "behaviorPack",
                        selected: behaviorPack,
                    },
                    {
                        title: "Resource pack",
                        value: "resourcePack",
                        selected: resourcePack,
                    },
                    {
                        title: "Advanced setup",
                        value: "advanced",
                        selected: false,
                    },
                ],
                hint: "- Space to select. Enter to confirm.",
                instructions: false,
            });
            const selected = new Set<string>(answers.features ?? []);
            behaviorPack = selected.has("behaviorPack");
            resourcePack = selected.has("resourcePack");
            advanced = selected.has("advanced");

            if (behaviorPack || resourcePack) {
                break;
            }

            console.log("[create] Select at least one content feature.");
        }
    }

    if (!behaviorPack && !resourcePack) {
        throw new Error(
            "A BlurEngine project must include at least one content pack: behavior or resource.",
        );
    }

    if (
        !skipPrompts &&
        advanced &&
        behaviorPack &&
        typeof options.scripts !== "boolean" &&
        !options.language
    ) {
        const scriptAnswers = await runPrompt({
            type: "multiselect",
            name: "features",
            message: "Enable advanced features",
            choices: [
                {
                    title: "Scripting",
                    value: "scripts",
                    selected: true,
                },
            ],
            hint: "- Space to select. Enter to confirm.",
            instructions: false,
        });
        const selected = new Set<string>(scriptAnswers.features ?? []);
        scripts = selected.has("scripts");
    }

    if (!behaviorPack) {
        scripts = false;
    }
    if (!scripts) {
        bebe = false;
    }

    if (scripts && !behaviorPack) {
        throw new Error("Scripting requires a behavior pack.");
    }

    if (
        !behaviorPack &&
        typeof options.scripts === "boolean" &&
        options.scripts
    ) {
        throw new Error("Cannot enable scripting without a behavior pack.");
    }

    if (!behaviorPack && typeof options.language === "string") {
        throw new Error("Cannot set --language without a behavior pack.");
    }

    if (!scripts && typeof options.language === "string") {
        throw new Error("Cannot set --language when scripting is disabled.");
    }
    if (!scripts && typeof options.bebe === "boolean" && options.bebe) {
        throw new Error("Cannot enable bebe when scripting is disabled.");
    }

    let languageInput = options.language;
    if (!skipPrompts && scripts && typeof options.bebe !== "boolean") {
        const answers = await runPrompt({
            type: "confirm",
            name: "bebe",
            message: "Use @blurengine/bebe runtime helpers?",
            initial: DEFAULT_CREATE_BEBE_ENABLED,
        });
        bebe = Boolean(answers.bebe ?? DEFAULT_CREATE_BEBE_ENABLED);
    }
    const shouldAskLanguage =
        !skipPrompts &&
        scripts &&
        !languageInput &&
        (advanced || typeof options.scripts === "boolean");
    if (shouldAskLanguage) {
        const answers = await runPrompt({
            type: "select",
            name: "language",
            message: "Script language",
            choices: [
                { title: "TypeScript", value: "ts" },
                { title: "JavaScript", value: "js" },
            ],
            initial: 0,
        });
        languageInput = String(answers.language ?? "");
    }

    let packageManagerInput = options.packageManager;
    if (!packageManagerInput && !skipPrompts) {
        const answers = await runPrompt({
            type: "select",
            name: "packageManager",
            message: "Package manager",
            choices: [
                { title: "npm", value: "npm" },
                { title: "pnpm", value: "pnpm" },
                { title: "yarn", value: "yarn" },
                { title: "bun", value: "bun" },
            ],
            initial: 0,
        });
        packageManagerInput = String(answers.packageManager ?? "");
    }

    let install = Boolean(options.install ?? true);
    if (typeof options.install === "undefined" && !skipPrompts) {
        const answers = await runPrompt({
            type: "confirm",
            name: "install",
            message: "Install dependencies after scaffolding?",
            initial: true,
        });
        install = Boolean(answers.install ?? true);
    }

    const normalizedDirectory = projectDirectory.replace(/[\\/]+$/, "");
    const projectName = path.basename(normalizedDirectory);
    const namespace = normalizeNamespace(namespaceInput);
    const packageManager = parsePackageManager(packageManagerInput) ?? "npm";
    const language = parseLanguage(languageInput) ?? "ts";

    if (!projectDirectory) {
        throw new Error(
            "Project name is required. Pass it as an argument or answer the prompt.",
        );
    }
    if (!projectName || projectName === "." || projectName === "..") {
        throw new Error(
            "Project name must resolve to a valid target directory name.",
        );
    }
    if (!namespace) {
        throw new Error(
            "Namespace is required. Use --namespace or answer the prompt.",
        );
    }
    assertValidNamespace(namespace);

    return {
        projectDirectory,
        projectName,
        namespace,
        packageManager,
        behaviorPack,
        resourcePack,
        scripts,
        bebe,
        language,
        force: Boolean(options.force),
        install,
    };
}

async function scaffoldProjectFiles(
    projectRoot: string,
    options: CreateResolvedOptions,
    cliVersion: string,
): Promise<void> {
    const packageName = toPackageName(options.projectName);
    const packName = toPackName(options.projectName);
    const entryFile = options.language === "ts" ? "src/main.ts" : "src/main.js";
    const packageJson = createPackageJson(
        options.projectName,
        packageName,
        options.packageManager,
        options.scripts,
        options.bebe,
        options.language,
        cliVersion,
    );
    const localOverrides = await resolveLocalDependencyOverrides(projectRoot);
    if (options.scripts && options.bebe) {
        Object.assign(packageJson.dependencies, localOverrides.dependencies);
    }
    Object.assign(packageJson.devDependencies, localOverrides.devDependencies);

    const behaviorPath = path.join(projectRoot, "behavior_packs", packName);
    const resourcePath = path.join(projectRoot, "resource_packs", packName);
    const blurConfig: BlurConfigFile = {
        $schema: BLR_CONFIG_SCHEMA_PATH,
        schemaVersion: 1,
        projectVersion: CURRENT_PROJECT_VERSION,
        namespace: options.namespace,
        minecraft: {
            channel: "stable",
            targetVersion: DEFAULT_MINECRAFT_TARGET_VERSION,
        },
    };

    await writeJson(path.join(projectRoot, "package.json"), packageJson);
    await writeJson(path.join(projectRoot, BLR_CONFIG_FILE), blurConfig);
    if (options.behaviorPack) {
        await writeJson(
            path.join(behaviorPath, "manifest.json"),
            createBehaviorManifest(
                options.projectName,
                [...DEFAULT_PACK_VERSION] as VersionTuple,
                options.scripts,
            ),
        );
    }
    if (options.resourcePack) {
        await writeJson(
            path.join(resourcePath, "manifest.json"),
            createResourceManifest(options.projectName, [
                ...DEFAULT_PACK_VERSION,
            ] as VersionTuple),
        );
    }

    if (options.scripts) {
        await writeText(
            path.join(projectRoot, entryFile),
            renderMainFile(options.bebe),
        );
    }

    await writeText(
        path.join(projectRoot, "README.md"),
        renderReadme(options.projectName, packName, options.packageManager, {
            behaviorPack: options.behaviorPack,
            resourcePack: options.resourcePack,
            scripts: options.scripts,
            bebe: options.bebe,
        }),
    );
    await writeText(
        path.join(projectRoot, ".gitignore"),
        reconcileManagedGitIgnore(undefined),
    );
    await syncManagedProjectInstructions(projectRoot, import.meta.url);

    if (options.scripts && options.language === "ts") {
        await writeText(
            path.join(projectRoot, "tsconfig.json"),
            renderTsConfig(),
        );
    }
}

function installDependencies(
    projectRoot: string,
    packageManager: PackageManager,
): void {
    const executable = resolvePmExecutable(packageManager);
    const result =
        process.platform === "win32"
            ? spawnSync(
                  "cmd.exe",
                  ["/d", "/s", "/c", `${executable} install`],
                  {
                      cwd: projectRoot,
                      stdio: "inherit",
                  },
              )
            : spawnSync(executable, ["install"], {
                  cwd: projectRoot,
                  stdio: "inherit",
              });

    if (result.error) {
        throw new Error(
            `Dependency installation failed with ${packageManager}: ${result.error.message}. Fix registry/auth config and run ${packageManager} install manually.`,
        );
    }

    if (result.status !== 0) {
        throw new Error(
            `Dependency installation failed with ${packageManager}. Fix registry/auth config and run ${packageManager} install manually.`,
        );
    }
}

export async function runCreateCommand(
    projectArg: string | undefined,
    options: CreateCommandOptions,
): Promise<void> {
    const resolved = await resolveCreateOptions(projectArg, options);
    const targetRoot = path.resolve(process.cwd(), resolved.projectDirectory);
    const cliVersion = await getCliPackageVersion();

    if (await exists(targetRoot)) {
        const empty = await isDirectoryEmpty(targetRoot);
        if (!empty && !resolved.force) {
            throw new Error(
                `Target directory already exists and is not empty: ${targetRoot}. Use --force to replace it.`,
            );
        }
        if (!empty && resolved.force) {
            await removeDirectory(targetRoot);
        }
    }

    await ensureDirectory(targetRoot);
    await scaffoldProjectFiles(targetRoot, resolved, cliVersion);

    if (resolved.install) {
        console.log(
            `[create] Installing dependencies with ${resolved.packageManager}...`,
        );
        installDependencies(targetRoot, resolved.packageManager);
    }

    console.log(`[create] Project generated at ${targetRoot}`);
    console.log("[create] Next steps:");
    console.log(`  cd ${resolved.projectDirectory}`);
    if (!resolved.install) {
        console.log(`  ${resolved.packageManager} install`);
    }
    console.log(`  ${resolved.packageManager} run dev`);
}
